---

- name: restart apache
  systemd:
    name: httpd
    state: restarted

- name: restart php-fpm
  systemd:
    name: rh-php71-php-fpm
    state: restarted

- name: restart icinga2
  systemd:
    name: icinga2
    state: restarted

- name: restart firewalld
  systemd:
    name: firewalld
    state: restarted

...
