---

- name: install icinga repo
  yum:
    name: "https://packages.icinga.com/epel/icinga-rpm-release-7-latest.noarch.rpm"
    state: installed

- name: install EPEL repo
  yum:
    name: epel-release
    state: installed

- name: install required packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - icinga2
    - icinga2-selinux
    - icingacli
    - icingaweb2
    - icingaweb2-selinux
    - nagios-plugins
    - nagios-plugins-ping
    - nagios-plugins-disk
    - nagios-plugins-procs
    - nagios-plugins-users
    - nagios-plugins-load
    - nagios-plugins-ssh
    - nagios-plugins-swap
    - nagios-plugins-http
    - nagios-plugins-dummy


- name: enable httpd
  systemd:
    name: httpd
    state: started
    enabled: yes

- name: set basic auth password
  htpasswd:
    path: /etc/icingaweb2/.http-users
    name: icingaadmin
    password: 'icingaadmin'
    owner: root
    group: icingaweb2
    mode: 0640

- name: configure auth for icingaweb2
  copy:
    src: authentication.ini
    dest: /etc/icingaweb2/authentication.ini
    owner: root
    group: icingaweb2
    mode: 0644

- name: configure web UI to use basic auth
  blockinfile:
    path: /etc/httpd/conf.d/icingaweb2.conf 
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    insertafter: '<Directory "/usr/share/icingaweb2/public">'
    content: |
      AuthType Basic
      AuthName "Icinga Web 2"
      AuthUserFile /etc/icingaweb2/.http-users
      Require valid-user
  notify:
  - restart apache

- name: copy PHP config
  copy:
    src: timezone.ini
    dest: /etc/php.d/timezone.ini
    owner: root
    group: root
    mode: 0644

- name: allow ports 22, 80, 443 through host firewall
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
      - http
      - https
      - ssh

...
