---

- name: install icinga repo
  yum:
    name: "https://packages.icinga.com/epel/icinga-rpm-release-7-latest.noarch.rpm"
    state: installed

- name: install EPEL, SCL repos
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - epel-release
    - centos-release-scl

- name: install Apache (may need to be installed before other packages)
  yum:
    name: httpd
    state: installed

- name: install required packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - icinga2
    - icinga2-ido-mysql
    - icinga2-selinux
    - icingacli
    - icingaweb2
    - icingaweb2-selinux
    - mariadb
    - mariadb-server
    - MySQL-python
    - nagios-plugins
    - nagios-plugins-ping
    - nagios-plugins-disk
    - nagios-plugins-procs
    - nagios-plugins-users
    - nagios-plugins-load
    - nagios-plugins-ssh
    - nagios-plugins-swap
    - nagios-plugins-http
    - nagios-plugins-dummy
    - php-pecl-imagick
    - sclo-php71-php-pecl-imagick
  notify: "restart php-fpm"

- name: enable servicves
  systemd:
    name: "{{ item }}" 
    state: started
    enabled: yes
  with_items:
    - httpd
    - icinga2
    - mariadb
    - rh-php71-php-fpm

- name: set basic auth password
  htpasswd:
    path: /etc/icingaweb2/.http-users
    name: icingaadmin
    password: 'icingaadmin'
    owner: apache
    group: icingaweb2
    mode: 0640

- name: copy config files for icingaweb2
  copy:
    src: "{{ item }}"
    dest: "/etc/icingaweb2/{{ item }}"
    owner: apache
    group: icingaweb2
    mode: 0660
  with_items:
    - authentication.ini
    - config.ini
    - resources.ini
    - roles.ini

- name: create enabledModules directory for icingaweb2
  file:
    path: "/etc/icingaweb2/enabledModules"
    state: directory
    owner: apache
    group: icingaweb2
    mode: 0750

- name: create module directories for icingaweb2
  file:
    path: "/etc/icingaweb2/modules/{{ item }}"
    state: directory
    owner: apache
    group: icingaweb2
    mode: 0760
  with_items:
    - monitoring

- name: copy module config files for icingaweb2
  copy:
    src: "monitoring/{{ item }}"
    dest: "/etc/icingaweb2/modules/monitoring/{{ item }}"
    owner: apache
    group: icingaweb2
    mode: 0660
  with_items:
    - backends.ini
    - commandtransports.ini
    - config.ini

- name: link from icingaweb2 enabledModules to modules
  file:
    src: "/usr/share/icingaweb2/modules/{{ item }}"
    dest: "/etc/icingaweb2/enabledModules/{{ item }}"
    owner: apache
    group: icingaweb2
    state: link
  with_items:
    - monitoring
    - setup

- name: configure web UI to use basic auth
  blockinfile:
    path: /etc/httpd/conf.d/icingaweb2.conf 
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    insertafter: '<Directory "/usr/share/icingaweb2/public">'
    content: |
      AuthType Basic
      AuthName "Icinga Web 2"
      AuthUserFile /etc/icingaweb2/.http-users
      Require valid-user
  notify:
  - restart apache

- name: require auth user for web UI
  lineinfile:
    path: /etc/httpd/conf.d/icingaweb2.conf
    insertbefore: 'Require all granted$'
    line: '            Require valid-user'

- name: copy PHP config
  copy:
    src: timezone.ini
    dest: /etc/opt/rh/rh-php71/php.d/40-timezone.ini
    owner: root
    group: root
    mode: 0644

- name: create MySQL database
  mysql_db:
    name: icingaweb2
    state: present
  register: mysql_db

- name: import MySQL schema
  mysql_db:
    name: icingaweb2
    state: import
    target: /usr/share/doc/icingaweb2/schema/mysql.schema.sql
  when: "mysql_db.changed"

- name: create ido-mysql database
  mysql_db:
    name: ido-mysql
    state: present
  register: ido_mysql

- name: import icinga-ido-mysql schema
  mysql_db:
    name: ido-mysql
    state: import
    target: /usr/share/icinga2-ido-mysql/schema/mysql.sql
  when: "ido_mysql.changed"

- name: add MySQL user to icingaweb2 DB
  mysql_user:
    name: icinga
    password: icinga
    host: localhost
    priv: "icingaweb2.*:ALL/ido-mysql.*:ALL"
    state: present

- name: enable icinga features
  command: "icinga2 feature enable {{ item }}"
  notify: restart icinga2
  with_items:
    - ido-mysql
#    - api

- name: copy ido-mysql config
  copy:
    src: ido-mysql.conf
    dest: /etc/icinga2/features-available/ido-mysql.conf
    owner: icinga
    group: icinga
    mode: 0640

- name: Add default Apache index page
  copy:
    src: index.html
    dest: /var/www/html/index.html

- name: allow ports 22, 80, 443 through host firewall
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
      - http
      - https
      - ssh

...
